services:
  db:
    image: postgres:16
    container_name: pg-test
    restart: always
    environment:
      POSTGRES_LOGGING: "on"
      POSTGRES_LOG_STATEMENT: "all"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "app_db"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: