version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env
    command: ./script.sh
    secrets:
      - my_secret

secrets:
  my_secret:
    file: /etc/secrets/.env