# Generated by Django 5.1 on 2024-11-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='battery_percentage',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='device',
            name='food_percentage',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='device',
            name='water_percentage',
            field=models.FloatField(default=100),
        ),
    ]
