# Generated by Django 5.1 on 2024-11-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0002_device_battery_percentage_device_food_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='battery_percentage',
        ),
        migrations.RemoveField(
            model_name='device',
            name='food_percentage',
        ),
        migrations.RemoveField(
            model_name='device',
            name='water_percentage',
        ),
        migrations.AddField(
            model_name='device',
            name='battery_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='food_limit',
            field=models.FloatField(default=500),
        ),
        migrations.AddField(
            model_name='device',
            name='food_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='water_limit',
            field=models.FloatField(default=1000),
        ),
        migrations.AddField(
            model_name='device',
            name='water_quantity',
            field=models.FloatField(default=0),
        ),
    ]
