# Generated by Django 5.1 on 2024-11-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0003_remove_device_battery_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagelog',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
